import { CodeBlock } from "@/components/code-block";
import { Table, TableBody, TableCell, TableRow } from "@/components/ui/table";
import { Doc, Ext, P, Page, Reference, WikiLink } from "@/components/wiki";
import { HOSTS } from "@/config";

const host = HOSTS.tetrapod.name;

export function SearxngPage() {
  return (
    <Page
      title="searxng"
      intro="private metasearch: no api keys, no rate limits from a provider, no tracking. one search box for humans, one json endpoint for every agent on the box."
    >
      <Doc title="humans">
        <P>
          <Ext url={`http://${HOSTS.tetrapod.fqdn}:8888`}>{host}:8888</Ext> — set it as a custom
          search engine in the browser if you like it.
        </P>
      </Doc>

      <Doc title="agents">
        <P>
          json api is on (that's the whole point). <WikiLink to="nullclaw">nullclaw</WikiLink>'s
          web_search points here; anything else can too:
        </P>
        <CodeBlock>{`curl "http://${host}:8888/search?q=lightpanda&format=json" | jq '.results[0]'`}</CodeBlock>
      </Doc>

      <Reference>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell className="text-muted-foreground">config</TableCell>
              <TableCell className="font-mono text-xs">
                provision/searxng/settings.yml (limiter off — single user)
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="text-muted-foreground">secret</TableCell>
              <TableCell className="font-mono text-xs">
                /opt/tetrapod/searxng.env (generated by bootstrap)
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="text-muted-foreground">image</TableCell>
              <TableCell className="font-mono text-xs">
                searxng/searxng:2026.7.19-6da6eee26
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Reference>
    </Page>
  );
}
