import { InlineCode } from "@/components/code-block";
import { Table, TableBody, TableCell, TableRow } from "@/components/ui/table";
import { Doc, Ext, P, Page, Reference } from "@/components/wiki";
import { HOSTS } from "@/config";

export function ZiplinePage() {
  return (
    <Page
      title="zipline"
      intro="screenshot and file host — shares that don't expire when discord's cdn feels like it. tailnet-only until the public domain gets wired."
    >
      <Doc title="setup state">
        <P>
          running at{" "}
          <Ext url={`http://${HOSTS.tetrapod.fqdn}:3200`}>{HOSTS.tetrapod.name}:3200</Ext>. first
          visit creates the admin account. the plan: a public route on tetraslam.world so share
          links are pretty — until then it's an internal stash.
        </P>
      </Doc>

      <Doc title="uploading">
        <P>
          web ui, or grab a token (settings → api) and point sharex/flameshot/a shell alias at{" "}
          <InlineCode>POST /api/upload</InlineCode>. worth scripting once the public domain exists.
        </P>
      </Doc>

      <Reference>
        <Table>
          <TableBody>
            <TableRow>
              <TableCell className="text-muted-foreground">image</TableCell>
              <TableCell className="font-mono text-xs">
                ghcr.io/diced/zipline:v4 (rolling — only channel tags exist)
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="text-muted-foreground">db</TableCell>
              <TableCell className="font-mono text-xs">
                postgres:16-alpine sidecar (zipline-db, docker-network only)
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="text-muted-foreground">secret</TableCell>
              <TableCell className="font-mono text-xs">
                /opt/tetrapod/zipline.env (CORE_SECRET, generated by bootstrap)
              </TableCell>
            </TableRow>
            <TableRow>
              <TableCell className="text-muted-foreground">uploads</TableCell>
              <TableCell className="font-mono text-xs">
                /opt/tetrapod/zipline/uploads (in nightly backups)
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </Reference>
    </Page>
  );
}
